### ISSUE TITLE
Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [frontiersi/Cliniface#1]
https://github.com/frontiersi/Cliniface/blob/92c51fb98aa671f82b07a432d8b719f390501880/CMakeLists.txt#L99

Please provide the AppImage for download on GitHub Releases, thank you.

**Comment by richeytastic** [comment]
[Here](https://github.com/frontiersi/Cliniface/releases/download/v3.2.1/cliniface-3.2.1.190226-x86_64-linux-gnu)
By the way, your tool is great - thanks a lot!

**Comment by probonopd** [comment]
Thank you.

**Comment by probonopd** [comment]
The AppImage is not working on Ubuntu trusty, the oldest still-supported Ubuntu release:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-10350/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#binaries-compiled-on-old-enough-base-system and https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by richeytastic** [comment]
Thanks for that - had to get this out quickly before being able to check earlier distros. I'll look into it.

**Comment by richeytastic** [comment]
Latest version is built and tested to work against Ubuntu Xenial. Thanks!

**Comment by probonopd** [comment]
Thank you very much :+1: 

Added to the catalog at https://appimage.github.io/Cliniface/.
