### ISSUE TITLE
AppImage gets aborted in Ubuntu Xenial

### ISSUE THREAD

**Issue by zenny** [frontiersi/Cliniface#2]
Hi,

Downloaded the AppImage and tried to run on command line in Ubuntu 16.04 as follows:

```
$  ./Cliniface-x86_64.AppImage 
======================================================================
 Cliniface 4.1.0.190921 <https://cliniface.org>
 Copyright 2018/2019 Spatial Information Systems Research Limited
 Developed by Richard Palmer
----------------------------------------------------------------------
 Cliniface is free software: you can redistribute it and/or modify it
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Cliniface is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 See the GNU General Public License for more details.
 You should have received a copy of the GNU General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
======================================================================
IDTFConverter : /tmp/.mount_ClinifD1c4Ir/usr/bin/u3dIntel/bin/IDTFConverter (available)
pdflatex      : /usr/bin/pdflatex (available)
Updating preferences at /home/zenny/.cliniface/preferences
Loading ethnicities...
Loading landmarks...
Loading metrics...
Loading phenotypes...
Loading genetics...
Loading syndromes...
Loading reports...
Aborted (core dumped)
```

Any clue?

**Comment by richeytastic** [comment]
Hi Zenny,

A bit weird... It should work fine on Xenial as long as you're running from a terminal within the Unity desktop. At the point its aborting, it's loading and rendering the UI for the first time after initialising so this strikes me as almost definitely something to do with your graphical rendering environment. I assume you're using Compiz as your window manager on a Unity desktop? You run other windowed graphical applications on your desktop without any issues?

Cliniface exposes a minimal command line interface for doing batch processing without opening the GUI so I'm wondering if I can get you to test it that way. If you can run Cliniface again, but this time with the one of its command line switches, that will cause it to run without trying to open the GUI. So do:
`$  ./Cliniface-x86_64.AppImage -m`

and see what you get. Output ought to be as follows (ignore the fact my pdflatex line is different). In particular, the "`-- Exiting --`" line indicates proper execution and cleanup.
```
IDTFConverter : /tmp/.mount_ClinifakZncd/usr/bin/u3dIntel/bin/IDTFConverter (available)
pdflatex      :  (not available)
Updating preferences at /home/rich/.cliniface/preferences
Loading ethnicities...
Loading landmarks...
Loading metrics...
Loading phenotypes...
Loading genetics...
Loading syndromes...
Loading reports...
-- Exiting --
```

Cheers,
Rich

**Comment by richeytastic** [comment]
Closing this issue now as a new version has been released. Please reopen if issue persists.
