### ISSUE TITLE
install on Mac

### ISSUE THREAD

**Issue by ReemShakir** [frontiersi/Cliniface#3]
Hi 
can I install Cliniface on MacOs ??

**Comment by Snipesengan** [comment]
try this https://github.com/frontiersi/Cliniface/releases/download/v5.3.2/Cliniface-x86_64.AppImage

**Comment by richeytastic** [comment]
Hi Reem,

Thanks for this message and your email. As per my email, your best option is to download the Linux version and use this within a Linux virtual machine. Currently there are no plans to develop a version for macOS.

Cheers,
Rich
